-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create profiles table with age-based categorization
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  birth_date date not null,
  age_category text not null check (age_category in ('criancas', 'adolescentes', 'jovens', 'adultos', 'casais')),
  is_admin boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create teams table
create table if not exists public.teams (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  color text not null default '#3B82F6',
  leader_id uuid references public.profiles(id) on delete set null,
  competition_mode text not null check (competition_mode in ('individual', '1v1', '2v2', '3v3', '4v4', '5v5')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create team members table
create table if not exists public.team_members (
  id uuid primary key default uuid_generate_v4(),
  team_id uuid references public.teams(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  joined_at timestamp with time zone default now(),
  unique(team_id, user_id)
);

-- Create questions table (generated by AI)
create table if not exists public.questions (
  id uuid primary key default uuid_generate_v4(),
  question_text text not null,
  correct_answer text not null,
  wrong_answers jsonb not null, -- Array of 3 wrong answers
  difficulty_level text not null check (difficulty_level in ('criancas', 'adolescentes', 'jovens', 'adultos', 'casais')),
  bible_reference text,
  topic text,
  created_at timestamp with time zone default now()
);

-- Create user progress table
create table if not exists public.user_progress (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade,
  current_level integer default 1,
  total_questions_answered integer default 0,
  correct_answers integer default 0,
  current_streak integer default 0,
  longest_streak integer default 0,
  last_quiz_date date,
  weekly_goal integer default 5,
  weekly_progress integer default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id)
);

-- Create quiz sessions table
create table if not exists public.quiz_sessions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade,
  team_id uuid references public.teams(id) on delete set null,
  competition_mode text check (competition_mode in ('individual', '1v1', '2v2', '3v3', '4v4', '5v5')),
  questions jsonb not null, -- Array of question IDs
  answers jsonb not null default '[]', -- Array of user answers
  score integer default 0,
  completed boolean default false,
  started_at timestamp with time zone default now(),
  completed_at timestamp with time zone
);

-- Create team rankings table
create table if not exists public.team_rankings (
  id uuid primary key default uuid_generate_v4(),
  team_id uuid references public.teams(id) on delete cascade,
  total_points integer default 0,
  total_wins integer default 0,
  total_matches integer default 0,
  rank integer,
  updated_at timestamp with time zone default now(),
  unique(team_id)
);

-- Create admin logs table
create table if not exists public.admin_logs (
  id uuid primary key default uuid_generate_v4(),
  admin_id uuid references public.profiles(id) on delete set null,
  action_type text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_team_id uuid references public.teams(id) on delete set null,
  description text not null,
  metadata jsonb,
  created_at timestamp with time zone default now()
);

-- Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.questions enable row level security;
alter table public.user_progress enable row level security;
alter table public.quiz_sessions enable row level security;
alter table public.team_rankings enable row level security;
alter table public.admin_logs enable row level security;

-- Profiles policies
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "Users can view other profiles"
  on public.profiles for select
  using (true);

-- Teams policies
create policy "Anyone can view teams"
  on public.teams for select
  using (true);

create policy "Team leaders can update their teams"
  on public.teams for update
  using (auth.uid() = leader_id);

create policy "Users can create teams"
  on public.teams for insert
  with check (auth.uid() = leader_id);

create policy "Team leaders can delete their teams"
  on public.teams for delete
  using (auth.uid() = leader_id);

-- Team members policies
create policy "Anyone can view team members"
  on public.team_members for select
  using (true);

create policy "Team leaders can add members"
  on public.team_members for insert
  with check (
    exists (
      select 1 from public.teams
      where id = team_id and leader_id = auth.uid()
    )
  );

create policy "Team leaders can remove members"
  on public.team_members for delete
  using (
    exists (
      select 1 from public.teams
      where id = team_id and leader_id = auth.uid()
    )
  );

create policy "Users can leave teams"
  on public.team_members for delete
  using (auth.uid() = user_id);

-- Questions policies (everyone can read)
create policy "Anyone can view questions"
  on public.questions for select
  using (true);

create policy "Only admins can create questions"
  on public.questions for insert
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

-- User progress policies
create policy "Users can view their own progress"
  on public.user_progress for select
  using (auth.uid() = user_id);

create policy "Users can update their own progress"
  on public.user_progress for update
  using (auth.uid() = user_id);

create policy "Users can create their own progress"
  on public.user_progress for insert
  with check (auth.uid() = user_id);

-- Quiz sessions policies
create policy "Users can view their own sessions"
  on public.quiz_sessions for select
  using (auth.uid() = user_id);

create policy "Users can create their own sessions"
  on public.quiz_sessions for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own sessions"
  on public.quiz_sessions for update
  using (auth.uid() = user_id);

-- Team rankings policies (everyone can read)
create policy "Anyone can view team rankings"
  on public.team_rankings for select
  using (true);

-- Admin logs policies
create policy "Admins can view all logs"
  on public.admin_logs for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can create logs"
  on public.admin_logs for insert
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );
